# Generated by Django 5.1.6 on 2025-03-02 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app_service', '0002_alter_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
    ]
