# Generated by Django 5.1.6 on 2025-03-03 15:24

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app_service', '0003_alter_medicalrecord_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='archived',
            new_name='is_service_archived',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='service_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='discount_group',
        ),
        migrations.AddField(
            model_name='patient',
            name='benefit_group',
            field=models.CharField(blank=True, choices=[('military', 'Військові (знижка 20%)'), ('elderly', 'Люди похилого віку (знижка 10%)'), ('disabled', 'Люди з інвалідністю (знижка 5%)'), ('staff_family', 'Члени родин працівників (знижка 40%)')], max_length=50, verbose_name='Пільгова група'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проведення'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата виконання'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оплати'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor_conclusion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Висновок лікаря'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='pdf_links',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Посилання на PDF-файли'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='services',
            field=models.ManyToManyField(related_name='medical_records', to='clinic_app_service.service', verbose_name='Необхідні обстеження'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('man', 'Чоловіча'), ('female', 'Жіноча')], max_length=8, verbose_name='Стать'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='По батькові'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='archive_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина архівування'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Є архівованим'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва прайс-листу'),
        ),
        migrations.AlterField(
            model_name='pricelistentry',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Вартість'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='По батькові'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qualification',
            field=models.CharField(max_length=255, verbose_name='Кваліфікація'),
        ),
    ]
