# Generated by Django 5.1.6 on 2025-03-03 17:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app_service', '0004_rename_archived_service_is_service_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='price_list_entry',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic_app_service.pricelistentry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сума без знижки'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сума зі знижкою'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='archive_reason',
            field=models.TextField(blank=True, max_length=255, verbose_name='Причина архівування'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('inactive', 'Неактивний')], default='Неактивний', max_length=15, verbose_name='Стан'),
        ),
    ]
