# Generated by Django 5.1.6 on 2025-03-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app_service', '0005_remove_appointment_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('man', 'Чоловіча'), ('female', 'Жіноча')], default='Чоловіча', max_length=8, verbose_name='Стать'),
        ),
    ]
