# Generated by Django 5.1.6 on 2025-03-05 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app_service', '0006_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic_app_service.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default=' ', max_length=255, verbose_name='По батькові'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('REGISTRAR', 'Реєстратор'), ('CLINIC_HEAD', 'Керівник'), ('DOCTOR', 'Лікар')], max_length=255, verbose_name='Тип користувача'),
        ),
    ]
