# Generated by Django 5.1.6 on 2025-03-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app_service', '0007_alter_appointment_doctor_alter_user_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('MAN', 'Чоловіча'), ('FEMALE', 'Жіноча')], default='Чоловіча', max_length=8, verbose_name='Стать'),
        ),
    ]
