# Generated by Django 5.1.6 on 2025-03-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app_service', '0010_alter_patient_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='archivation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архівування'),
        ),
    ]
