# Generated by Django 5.1.6 on 2025-03-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app_service', '0011_pricelist_archivation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='execution_status',
            field=models.CharField(choices=[('PLANNED', 'Запланований'), ('CANCELED', 'Скасований'), ('COMPLETED', 'Завершений')], default='PLANNED', max_length=15, verbose_name='Стан виконання'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активний'), ('INACTIVE', 'Неактивний')], default='INACTIVE', max_length=15, verbose_name='Стан'),
        ),
    ]
