# Generated by Django 5.1.6 on 2025-03-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app_service', '0012_alter_appointment_execution_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Чоловіча'), ('FEMALE', 'Жіноча')], default='Чоловіча', max_length=8, verbose_name='Стать'),
        ),
    ]
