# Generated by Django 5.1.6 on 2025-03-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app_service', '0013_alter_patient_gender'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicalrecord',
            name='check_diagnosis_doctor_conclusion',
        ),
        migrations.RemoveConstraint(
            model_name='medicalrecord',
            name='check_analysis_pdf_links',
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('ANALYSIS_RESULTS', 'Результати аналізів'), ('NECESSARY_EXAMINATIONS', 'Направлення'), ('DIAGNOSIS', 'Діагноз')], max_length=255, verbose_name='Тип запису'),
        ),
        migrations.AddConstraint(
            model_name='medicalrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('record_type', 'DIAGNOSIS'), models.Q(('doctor_conclusion', None), _negated=True)), models.Q(('record_type', 'DIAGNOSIS'), _negated=True), _connector='OR'), name='check_diagnosis_doctor_conclusion'),
        ),
        migrations.AddConstraint(
            model_name='medicalrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('record_type', 'ANALYSIS_RESULTS'), models.Q(('pdf_links', None), _negated=True)), models.Q(('record_type', 'ANALYSIS_RESULTS'), _negated=True), _connector='OR'), name='check_analysis_pdf_links'),
        ),
    ]
