# Generated by Django 5.1.6 on 2025-03-06 16:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app_service', '0014_remove_medicalrecord_check_diagnosis_doctor_conclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='title',
            field=models.CharField(default='-', max_length=255, verbose_name='Назва запису'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='pdf_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Посилання на PDF-файли'),
        ),
    ]
