# Generated by Django 5.1.6 on 2025-03-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app_service', '0015_medicalrecord_title_alter_medicalrecord_pdf_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код верифікації'),
        ),
    ]
