# Generated by Django 5.1.6 on 2025-03-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app_service', '0016_user_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Email')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='Verification code')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
    ]
